### PR TITLE
Error detection and handling of statistics plugin

### LINKED ISSUE #145: More meaningful error messages in statistics plugin
Currently, the error messages in the statistics plugin are usually something between non-existent and useless.

For example, in case the `affiliation` field for a person has the wrong key, which is not found in the institutes database, a low-level Ruby exception is thrown without any pointer to the actual source of the error.

We should have better parameter checking and useful error messages in the statistics plugin to point the user to the person causing the error.

> _@isabelheisters, I know you are already working on that. This issue is just for documentation purposes_

### PR DESCRIPTION
**Pull request by isabelheisters**
fixes #145 
@torbjoernk Can you please have a look?

Signed-off-by: Isabel Heisters i.heisters@fz-juelich.de

### CODE REVIEW

File: _plugins/statistics_tag.rb [hunk 1]
```diff
@@ -16,6 +23,16 @@ def self.get_stats(site)
         'states' => {}
     }
 
+    unless institutes.has_key?(people['institutes'])
```
Comment (torbjoernk) [inline _plugins/statistics_tag.rb]: that's not what I meant to test for ...

File: _plugins/statistics_tag.rb [hunk 2]
```diff
@@ -16,6 +23,16 @@ def self.get_stats(site)
...
+      raise StatisticsError.new 'Institute not found. Typo? Look at data/institutes.yml!'
+    end
+
+    unless people['position'].is_nil?
```
Comment (torbjoernk) [inline _plugins/statistics_tag.rb]: ... neither this.

We should check below in `people.each`, whether `institutes.has_key? person['affiliation']` and `positions.has_key? person['position']`. That's where actual user input is used as keys of pre-constructed maps.

File: _plugins/statistics_tag.rb [hunk 3]
```diff
@@ -16,6 +23,16 @@ def self.get_stats(site)
...
+      unless positions.has key?(people['position'])
```
Comment (torbjoernk) [inline _plugins/statistics_tag.rb]: (looks like a typo here)

**Comment by torbjoernk** [comment]
Looks great so far :+1:. A few points still to tune :-)
1. What about rewording the error messages:
   
   > Institute 'ERRORNOUS_ID' of person 'ID' not found. Typo? See '_data/institutes.yml'.
2. same for position

Hint: `kalbarczyk_z` seems to be a good candidate for testing, as he is not yet used in any person tags.

**Comment by torbjoernk** [comment]
LGTM. Could you please add checks further down where the people, topics and states of the projects are parsed? I.e. line 82, 95, 110 and 116.

**Comment by torbjoernk** [comment]
Thanks a lot, @isabelheisters ! :+1:
